@startuml
skinparam packageStyle rectangle
/' Nodes '/
/'  Drivers & History Projects '/
package driver_history_demux{
object vrpn_analog_driver
vrpn_analog_driver : DriverSensor
vrpn_analog_driver : driver = XBOXCONTROLLER
vrpn_analog_driver : sensor = 0
vrpn_analog_driver : type = ANALOG

object vrpn_analog_data
vrpn_analog_data : HistoryProject
vrpn_analog_data : project >VALUE, CHANNELS<

object vrpn_button_driver
vrpn_button_driver : DriverSensor
vrpn_button_driver : driver = XBOXCONTROLLER
vrpn_button_driver : sensor = 0
vrpn_button_driver : type = BUTTON

object vrpn_button_data
vrpn_button_data : HistoryProject
vrpn_button_data : project >BTMASK, NUMBER, STATE<

object btn_number_to_int
btn_number_to_int : TypeConvert[unsigned int,int]

object get_button
get_button : Demultiplex[unsigned int]
get_button : num_outports >14<
}

/'  observer node '/
object observer
observer : ObserverNavigationNode
observer : max_linear_speed = 10, 10, 10
observer : max_angular_speed = 1

/'  timer node for observer '/
object timer
timer : Timer

/'  Compose movement vector for observer '/
package movement_composition{
/'      Triggers for moving forward/zooming '/
object triggers_to_float
triggers_to_float : TypeConvert[double,float]

/'      Strafing using the Right Stick '/
object RStickX_to_float
RStickX_to_float : TypeConvert[double,float]

object negate_RStickY
negate_RStickY : Negate[double]

object RStickY_to_float
RStickY_to_float : TypeConvert[double,float]

/'      compile into vector '/
object movement
movement : Compose3DVector
}

/'  Compose rotation for observer '/
package rotation_composition{
/'      Rolling using the bumpers '/
object roll_movement
roll_movement : Subtract[float]

object lb_to_float
lb_to_float : TypeConvert[unsigned int,float]
object rb_to_float
rb_to_float : TypeConvert[unsigned int,float]

object rotation_axis
rotation_axis : ConstantValue[VistaVector3D]
rotation_axis : value = 0,0,-1,0

/'      compile into rotation '/
object rotation
rotation : AxisRotate
}

/'  Compose pitch control from left stick y axis '/
package pitch_control{
object pitch_axis
pitch_axis : ConstantValue[VistaVector3D]
pitch_axis : value = -1,0,0,0

object pitch_to_float
pitch_to_float : TypeConvert[double,float]

object pitch_rotation
pitch_rotation : AxisRotate
}

/'  Compose yaw control from left stick x axis '/
package yaw_control{
object yaw_axis
yaw_axis : ConstantValue[VistaVector3D]
yaw_axis : value = 0,-1,0,0

object yaw_to_float
yaw_to_float : TypeConvert[double,float]

object yaw_rotation
yaw_rotation : AxisRotate
}

/'  Compile rotations together'/
package compile_rotations{
object pitch_yaw
pitch_yaw : Multiply[VistaQuaternion]

object pitch_yaw_roll
pitch_yaw_roll : Multiply[VistaQuaternion]
}

/' Edges '/
/'  Driver, History, and Button Demux '/
vrpn_button_driver "history" --> "history" vrpn_button_data
vrpn_button_data "NUMBER" --> "in" btn_number_to_int
btn_number_to_int "out" --> "select" get_button
vrpn_button_data "STATE" --> "value" get_button

vrpn_analog_driver "history" --> "history" vrpn_analog_data

/'  Feed composed movements into observer '/
timer "time" --> "time" observer
movement "out" --> "translation" observer


/'  Compose forward movement (zooming) '/
vrpn_analog_data "VALUE_4" --> "in" triggers_to_float
triggers_to_float "out" --> "z" movement

/'  Compose horizontal movement (strafing) '/
vrpn_analog_data "VALUE_2" --> "in" RStickX_to_float
RStickX_to_float "out" --> "x" movement

/'  Compose vertical movement (strafing) '/
vrpn_analog_data "VALUE_3" --> "in" negate_RStickY
negate_RStickY "out" --> "in" RStickY_to_float
RStickY_to_float "out" --> "y" movement

/'  Compose rotation (roll) for observer '/
get_button "4" --> "in" lb_to_float
get_button "5" --> "in" rb_to_float
lb_to_float "out" --> "second" roll_movement
rb_to_float "out" --> "first" roll_movement
roll_movement "out" --> "angle" rotation
rotation_axis "value" --> "axis" rotation

/'  Compose pitch control from left stick y axis '/
vrpn_analog_data "VALUE_1" --> "in" pitch_to_float
pitch_to_float "out" --> "angle" pitch_rotation
pitch_axis "value" --> "axis" pitch_rotation

/'  Compose yaw control from left stick x axis '/
vrpn_analog_data "VALUE_0" --> "in" yaw_to_float
yaw_to_float "out" --> "angle" yaw_rotation
yaw_axis "value" --> "axis" yaw_rotation

/'  Compile rotations together '/
pitch_rotation "out" --> "first" pitch_yaw
yaw_rotation "out" --> "second" pitch_yaw
pitch_yaw "out" --> "first" pitch_yaw_roll
rotation "out" --> "second" pitch_yaw_roll
pitch_yaw_roll "out" --> "rotation" observer
@enduml
