@startuml
skinparam packageStyle rectangle
/' Nodes '/
package driver_history{
object mouse #lightblue
mouse : DriverSensor

object project_mouse
project_mouse : HistoryProject
}

package scrollwheel {
object wheel_change_detect
wheel_change_detect : ChangeDetect[int]

object wheel_value
wheel_value : Difference[int]

object scroll_wheel #red
scroll_wheel : EventSource
}

package buttons {
object left_button_change_detect
left_button_change_detect : ChangeDetect[bool]

object right_button_change_detect
right_button_change_detect : ChangeDetect[bool]

object middle_button_change_detect
middle_button_change_detect : ChangeDetect[bool]

object button_01 #red
button_01 : EventSource

object button_02 #red
button_02 : EventSource

object button_03 #red
button_03 : EventSource
}

/' store position for 3dmouse_negotiator '/
package 3dmouse_output{
object set_mouse_xpos #red
set_mouse_xpos : SetVariable[int]
set_mouse_xpos : variable = mouse_xpos

object set_mouse_ypos #red
set_mouse_ypos : SetVariable[int]
set_mouse_ypos : variable = mouse_ypos
}
/' Edges '/
mouse "history" --> "history" project_mouse

project_mouse "WHEEL_STATE" --> "in" wheel_change_detect
wheel_change_detect "out" --> "in" wheel_value
wheel_value "out" --> "value" scroll_wheel

project_mouse "LEFT_BUTTON" --> "in" left_button_change_detect
left_button_change_detect "out" --> "value" button_01

project_mouse "RIGHT_BUTTON" --> "in" right_button_change_detect
right_button_change_detect "out" --> "value" button_02

project_mouse "MIDDLE_BUTTON" --> "in" middle_button_change_detect
middle_button_change_detect "out" --> "value" button_03

/' compose positions to vector '/
project_mouse "X_POS" --> "value" set_mouse_xpos
project_mouse "Y_POS" --> "value" set_mouse_ypos
@enduml
