@startuml
skinparam packageStyle rectangle
/' Nodes '/
package driver_history{
object mouse #lightblue
mouse : DriverSensor

object project_mouse
project_mouse : HistoryProject
}

package scrollwheel {
object wheel_change_detect
wheel_change_detect : ChangeDetect[int]

object wheel_value
wheel_value : Difference[int]

object scroll_wheel #red
scroll_wheel : EventSource
}

package buttons {
object left_button_change_detect
left_button_change_detect : ChangeDetect[bool]

object right_button_change_detect
right_button_change_detect : ChangeDetect[bool]

object middle_button_change_detect
middle_button_change_detect : ChangeDetect[bool]

object button_01 #red
button_01 : EventSource

object button_02 #red
button_02 : EventSource

object button_03 #red
button_03 : EventSource
}

/' store position for 3dmouse_negotiator '/
package 3dmouse_output{
object compose_pos_vector
compose_pos_vector : Compose3DVector

object set_mouse_pos #red
set_mouse_pos : SetVariable[VistaVector3D]
set_mouse_pos : variable = mouse_pos

object const_0 #lightblue
const_0 : ConstantValue[float]
const_0 : value = 0

object xpos_to_float
xpos_to_float : TypeConvert[int,float]

object ypos_to_float
ypos_to_float : TypeConvert[int,float]
}
/' Edges '/
mouse "history" --> "history" project_mouse

project_mouse "WHEEL_STATE" --> "in" wheel_change_detect
wheel_change_detect "out" --> "in" wheel_value
wheel_value "out" --> "value" scroll_wheel

project_mouse "LEFT_BUTTON" --> "in" left_button_change_detect
left_button_change_detect "out" --> "value" button_01

project_mouse "RIGHT_BUTTON" --> "in" right_button_change_detect
right_button_change_detect "out" --> "value" button_02

project_mouse "MIDDLE_BUTTON" --> "in" middle_button_change_detect
middle_button_change_detect "out" --> "value" button_03


/' compose positions to vector '/
project_mouse "X_POS" --> "in" xpos_to_float
xpos_to_float "out" --> "x" compose_pos_vector
project_mouse "Y_POS" --> "in" ypos_to_float
ypos_to_float "out" --> "y" compose_pos_vector
const_0 "value" --> "z" compose_pos_vector

/' save vector to variable '/
compose_pos_vector "out" --> "value" set_mouse_pos
@enduml
